import React, { useState, useEffect } from 'react';
import api from '../api/axios';
import styles from './Case.module.css';

const AICaseSummary = ({ caseId, userRole }) => {
    const [summary, setSummary] = useState(null);
    const [loading, setLoading] = useState(true);
    const [generating, setGenerating] = useState(false);
    const [error, setError] = useState(null);

    const fetchSummary = async () => {
        try {
            setLoading(true);
            const res = await api.get(`/ai/case-summary/${caseId}`);
            setSummary(res.data);
        } catch (error) {
            console.error("Failed to fetch AI summary", error);
            setError("Failed to load existing summary.");
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        if (caseId) fetchSummary();
    }, [caseId]);

    const handleGenerate = async () => {
        try {
            setGenerating(true);
            setError(null);
            const res = await api.post(`/ai/case-summary/${caseId}`);
            setSummary(res.data);
        } catch (error) {
            console.error("Failed to generate AI summary", error);
            setError("Failed to generate AI summary. Ensure the API key is valid and the server is running.");
        } finally {
            setGenerating(false);
        }
    };

    if (loading) return <div className={styles.container}>Loading AI Summary...</div>;

    // Formatting markdown headers to basic HTML
    const renderMarkdown = (text) => {
        if (!text) return null;
        return text.split('\n').map((line, index) => {
            if (line.startsWith('### ')) {
                return <h3 key={index} style={{ color: '#1e293b', marginTop: '1.5rem', borderBottom: '1px solid #e2e8f0', paddingBottom: '0.5rem' }}>{line.replace('### ', '')}</h3>;
            } else if (line.startsWith('**') && line.includes('**:')) {
                const parts = line.split('**:');
                return <p key={index}><strong style={{ color: '#334155' }}>{parts[0].replace('**', '')}:</strong>{parts[1]}</p>;
            } else if (line.startsWith('* ')) {
                return <li key={index} style={{ marginLeft: '20px', marginBottom: '5px', color: '#475569' }}>{line.replace('* ', '')}</li>;
            } else if (line.trim() === '') {
                return <br key={index} />;
            }
            return <p key={index} style={{ color: '#475569', lineHeight: '1.6' }}>{line}</p>;
        });
    };

    return (
        <div className={styles.container} style={{ backgroundColor: '#f8fafc' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                <h2 className={styles.heading} style={{ margin: 0 }}>
                    <span style={{ fontSize: '1.5rem', marginRight: '10px' }}>✨</span> 
                    AI Case Summary
                </h2>
                
                {(userRole === 'admin' || userRole === 'lawyer' || userRole === 'judge') && (
                    <button 
                        onClick={handleGenerate} 
                        disabled={generating}
                        className={styles.submitBtn} 
                        style={{ width: 'auto', margin: 0, backgroundColor: generating ? '#94a3b8' : '#8b5cf6' }}
                    >
                        {generating ? 'Generating (Please wait)...' : summary ? '🔄 Refresh Summary' : '✨ Generate AI Summary'}
                    </button>
                )}
            </div>

            {error && <div style={{ backgroundColor: '#fee2e2', color: '#b91c1c', padding: '10px', borderRadius: '5px', marginBottom: '15px' }}>{error}</div>}

            <div style={{ backgroundColor: '#ffffff', padding: '30px', borderRadius: '8px', border: '1px solid #e2e8f0', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)' }}>
                {!summary ? (
                    <div style={{ textAlign: 'center', color: '#94a3b8', padding: '40px 0' }}>
                        <h3 style={{ margin: '0 0 10px 0' }}>No AI Summary Available</h3>
                        <p>Click "Generate AI Summary" to analyze the case data and generate a comprehensive overview.</p>
                    </div>
                ) : (
                    <div>
                        <div style={{ marginBottom: '20px', paddingBottom: '15px', borderBottom: '1px dashed #cbd5e1', color: '#64748b', fontSize: '0.9rem', display: 'flex', justifyContent: 'space-between' }}>
                            <span>Generated By: {summary.generatedBy?.username || 'System'} ({summary.generatedBy?.role})</span>
                            <span>Last Updated: {new Date(summary.updatedAt).toLocaleString()}</span>
                        </div>
                        
                        <div className="ai-content">
                            {renderMarkdown(summary.summary)}
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default AICaseSummary;
